/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Display */

#ifndef _Included_Display
#define _Included_Display
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Display
 * Method:    displayLine
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Display_displayLine
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
